export const TAGS = [
  ".NET",
  "3D Modeling",
  "3D Rendering",
  "Agile Development",
  "Algorithms",
  "Android",
  "Artificial Intelligence",
  "Assembly Programming",
  "Automata",
  "Biological Modeling",
  "C++",
  "C#",
  "Client-Side",
  "Cognitive Science",
  "Code Generation",
  "Computation",
  "Compilers",
  "Computational Biology",
  "Concurrency",
  "Cryptography",
  "Data Analysis",
  "Data Modeling",
  "Data Structures",
  "Databases",
  "DMD",
  "Distributed Systems",
  "Embedded Software",
  "Final Report",
  "Foundations",
  "Functional Programming",
  "Hardware",
  "Haskell",
  "Information Science",
  "Information Systems",
  "Intermediate",
  "Interdisciplinary",
  "Interpreters",
  "Introductory",
  "iOS",
  "Java",
  "JavaScript",
  "Kinematics",
  "Life-Critical Systems",
  "Linux",
  "Logic",
  "Machine Learning",
  "Mathematical Foundations",
  "Mathematics",
  "Mobile Development",
  "Network Security",
  "Neuroscience",
  "Object-Oriented",
  "Operating Systems",
  "Parallelism",
  "Perception",
  "Planning Algorithms",
  "Policy",
  "Probability",
  "Programming Fundamentals",
  "Programming Languages",
  "Project Presentation",
  "Python",
  "Quantum Computing",
  "Quantum Mechanics",
  "Rails",
  "Randomized Algorithms",
  "Ray Tracing",
  "Robotics",
  "Ruby",
  "Rust",
  "Scalability",
  "Search",
  "Senior Project",
  "Scripting",
  "Software",
  "Software Design",
  "Software Engineering",
  "Software Security",
  "Statistics",
  "Supervised Learning",
  "Systems Programming",
  "Technology",
  "Testing",
  "Technical Skills",
  "Unix",
  "Unsupervised Learning",
  "Verification",
  "Virtual Memory",
  "Web Development",
];

export const TAXES: { [key: number]: string } = {
  1: "😁",
  2: "🙂",
  3: "🙁",
  4: "😬",
  5: "😢",
  6: "😫",
  7: "😭",
};
